# Generated by Django 4.0.2 on 2022-03-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLDR', '0005_alter_pressrelease_pressreleasedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressrelease',
            name='PressReleaseImage',
            field=models.TextField(null=True),
        ),
    ]
